server:
  port: 9001
spring:
  application:
    name: yougou-brand #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pinyougoudb?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  thymeleaf:
    mode: HTML
    prefix: classpath:/static/
    suffix: .html
